language: php
php:
- 7.2
services:
- mysql
before_script:
- composer install
script: "./vendor/bin/phpunit ./tests"
deploy:
  provider: heroku
  app: curso-github-cefire
  on: master
  skip_cleanup: true
  api_key:
    secure: Rrod5u1EqT25XkGDrY3DzSoj9gGxT2R+OJZXza9S7x5NOZMiXOjeNKtwt+Z4hcqQT/4/FInfDNXZdIfBrhDreHMYUPuu3115Fpk2AmwqtXGhBbeVBwGneaPVIF8LeUaRYwfhQl27Cobq0wkC05q3q69FhG+6PDfaH6TkAmbvJauZpA87kK7iKQXM+885gh2YvoDcLQoe9x6zxk7I8wpnYX+aIfzhbOd63jPLpWCJYr7ggYXaHPTlYsCmucLa/4JcBSGoA7xePMN++kqvK4cl0xVeQZloVFdD3t16ZHiL8/nFMBoH1McCFBUdaz+gvcLeIoGfJzSY2ZNY8+Q8OcylZZk3sGkYg9pXAQeyxTsBIf189ry8yMpyJUU+P4MEcajToXmpPtvnLYfI9BvKcWS0+iVQENgu+iyWSR2QELSrtqB3U2X9QzK44tJwAa3yPW91gyRHZS0R5qZkTD+UjI5ja+cxnRsGLvtIBJyiPfSanKFC80qeTYLAcirdl/Meo2mkP5RTEFiNtwRmq53Evcuw2fN/hZo2lHHwRpyNYx6RJlOAtaWAHdLIAPhbIHug6Ni7w/VwbamLpz1IuMq/xAXkrrSzS2ZrlVotwOAyrEkEofGomUa1kSxv/7C1kPETFtNWN7fx0NUaFXujrkViX0lsOFwchjUPvFAk5ZaXIS6ZnkI=
